### ISSUE TITLE
 Looking for some extra help

### ISSUE THREAD

**Issue by lionheart2133** [jeremysherriff/OpenFLIXR2.CustomScripts#2]
# SOME REASON
Before that I used transmission,and there is a tool called transmission-remote,which is very convenient for seed management.
But I have to use qbittorrent for connectivity reasons. I found that according to official documents, I have to use post requests,but I didn't know anything about it,just know little shell and python.when looking for information in the forum, I found this relatively similar project(completed remove).

# WHAT I WANT TO ACHIEVE
**changing the save path when the torrent is finished,And it won't stop seeding.**
such as 
`aaa/download/music/maroon5`
to
`aaa/completed/music/maroon5`
I noticed that QBIT can pass some variables after the seed is finished. I think that processing these string variables can achieve the goal well.e.g:
```
%N:Torrent name
%G: tags (separated by commas)
%F: content path (same as the root of the multi-file torrent)
%R: root directory (subdirectory path of the first torrent)
%D: save path
%I: hashes
```
But I really don't know how to complete this complex script.

hope to get some help from you.Thanks a million!

**Comment by jeremysherriff** [comment]
I'm pretty sure there's scripts available all over the internet that deal with post-processing, and sonarr/radarr/lidarr all deal with it natively inside the application that you can use a web browser to configure.
