### ISSUE TITLE
Script request

### ISSUE THREAD

**Issue by Jorman** [jeremysherriff/OpenFLIXR2.CustomScripts#3]
Hi, sorry if I open a new issue, I can't find a way to write you an email.

First of all, thanks for your script to clean complete torrent from qbittorrent, I think is pretty cool, because if I want to use with sonarr and company I've to set qbt to pause stop the torrent so if I download other file qbt never delete it!

Btw I write to you to ask you if you know or if you plan a script to inject tracker inside torrent.
I know that qbt already offer a function like that but tracker list is always updating so I search a "better" solution in order to have the tracker list parsed from an online list. In a short word I want to make it like this script
https://github.com/Jorman/Scripts/blob/master/AddTransmissionTrackers.sh
This take a list from a git and if the torrent is not "private" inject all the tracker inside the torrent, I usually call it from sonarr, radarr and co

What do you think?

J

**Comment by jeremysherriff** [comment]
Sorry, I have no plans for further scripting. The project that this script base was around (openflixr) is no longer used by me.

You can use the functional parts of this script to achieve what you want, there's no need for me to code it for you. Having an actual useful goal is the best way to learn such a scripting language.
