### ISSUE TITLE
4.5 version of BitTorrent breaks this script

### ISSUE THREAD

**Issue by hstorey219** [jeremysherriff/OpenFLIXR2.CustomScripts#4]
[clear_qbt_complete.py](https://github.com/jeremysherriff/OpenFLIXR2.CustomScripts/blob/master/clear_qbt_complete.py)

After updating to this version, I see this in the log file

2022-12-03 13:52:02,845 [INFO ] Clearing pausedUP torrent + data: Gifted.2017.NORDiC.1080p.WEB-DL.H.265.DD5.1-TWA
2022-12-03 13:52:02,848 [ERROR] 405 Client Error: Method Not Allowed for url: http://localhost:8083/api/v2/torrents/delete?hashes=5ac727b33feeeac5e1748ce6d10c31791663a842&deleteFiles=true

**Comment by jeremysherriff** [comment]
Working ok for me. From some other tinkering I've done, I think 405 indicates you're not properly authenticated, do you have local access IP address in the auth whitelist?

**Comment by hstorey219** [comment]
> Working ok for me. From some other tinkering I've done, I think 405 indicates you're not properly authenticated, do you have local access IP address in the auth whitelist?

I found this https://github.com/qbittorrent/qBittorrent/issues/18097 Looks like Qbittorrent now requires you to use POST command instead of GET 
I still could not get it work with authenticated

**Comment by jeremysherriff** [comment]
Just realised I'm still on v4.4.5 so not affected by that API change.
I'll add a note to the repo and script.

**Comment by jeremysherriff** [comment]
Reading that issue over on the qbt repo, I think you'd be able to just switch `get` to `post` in line https://github.com/jeremysherriff/OpenFLIXR2.CustomScripts/blob/807f22e785677a7d5886258c1871f89302d3d38e/clear_qbt_complete.py#L74

I've not done a lot of POST calls, not sure if it needs additional parameters, but making it:
`response = requests.post(baseurl+url)`
might be sufficient.

**Comment by hstorey219** [comment]
> Reading that issue over on the qbt repo, I think you'd be able to just switch `get` to `post` in line
> 
> https://github.com/jeremysherriff/OpenFLIXR2.CustomScripts/blob/807f22e785677a7d5886258c1871f89302d3d38e/clear_qbt_complete.py#L74
> 
> I've not done a lot of POST calls, not sure if it needs additional parameters, but making it: `response = requests.post(baseurl+url)` might be sufficient.

Got it to work with this
import requests
import tor

BASE_URL = 'http://localhost:8083/'

endpoint = 'api/v2/torrents/delete'
payload = {"hashes": str(tor["hash"]),
"deleteFiles": True}

response = [requests.post](http://requests.post/)(f"{BASE_URL}{endpoint}", params=payload)

**Comment by jeremysherriff** [comment]
Just FYI, I've upgraded to qBT 4.5 and can confirm I'm now affected by the same issue. When I get a chance I'll look to take your learnings from above and merge them in. Thanks for the efforts.

**Comment by hstorey219** [comment]
Another work around
I believe I have identified the root cause of this problem.

The documentation clearly states that the delete call should be this:
/api/v2/torrents/delete?hashes=8c212779b4abde7c6bc608063a0d008b7e40ce32&deleteFiles=false
RE:
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#delete-torrents
That is incorrect.

The way this works is as follows.  The URL must be
/api/v2/torrents/delete
Then the parameters MUST be form variables, NOT JSON, but form variables.
If you sent it as form variables like this. then it works:
hashes=8c212779b4abde7c6bc608063a0d008b7e40ce32
deleteFiles=false

**Comment by jeremysherriff** [comment]
Do you want to give me your code that works?  I can't actually make it go, despite being able to use `curl` to do it quite successfully.

**Comment by jeremysherriff** [comment]
never mind, I'm an idiot - I've been trying for hours to get it to work with a `PUT` instead of a `POST`.

**Comment by jeremysherriff** [comment]
Two commits done;
- corrected the `delete` call to use POST, so works now with v4.5
- Corrected a logic flaw with setting up the logger that prevented error messages surfacing without `--verbose` being set, so v4.5 failures were not correctly reported under normal circumstances

One day i'll refactor to support the more modern string handling syntax, but today is not that day.
